---
language: node_js
node_js:
  - "5.0"

sudo: false
dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - "npm install -g npm@^2"
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: node_modules/.bin/ember deploy development --activate --verbose
    on:
      branch: development

after_deploy:
  - provider: script
    skip_cleanup: true
    script: perl scripts/run_tests.pl
    on:
      branch: development